INSERT INTO tb_questoes
(materia, nivel, assunto, pergunta, alternativa_a, alternativa_b, alternativa_c, alternativa_d, resposta_correta)
VALUES

('História','Ensino Médio','Revolução Francesa',
'Em que ano teve início a Revolução Francesa?',
'1776',
'1789',
'1804',
'1815',
'B'),

('História','Ensino Médio','Revolução Francesa',
'Qual era o lema da Revolução Francesa?',
'Ordem e Progresso',
'Liberdade, Igualdade e Fraternidade',
'Paz e Justiça',
'União e Trabalho',
'B'),

('História','Ensino Médio','Revolução Francesa',
'Qual era o nome da prisão tomada em 14 de julho de 1789?',
'Versalhes',
'Conciergerie',
'Bastilha',
'Louvre',
'C'),

('História','Ensino Médio','Revolução Francesa',
'Quem era o rei da França durante o início da Revolução Francesa?',
'Luís XIV',
'Luís XV',
'Luís XVI',
'Napoleão Bonaparte',
'C'),

('História','Ensino Médio','Revolução Francesa',
'Qual grupo social fazia parte do Terceiro Estado?',
'Nobreza',
'Alto Clero',
'Burguesia, camponeses e trabalhadores',
'Rei e família real',
'C'),

('História','Ensino Médio','Revolução Francesa',
'Qual documento proclamou direitos fundamentais durante a Revolução Francesa?',
'Declaração de Independência',
'Declaração dos Direitos do Homem e do Cidadão',
'Carta Magna',
'Tratado de Versalhes',
'B'),

('História','Ensino Médio','Revolução Francesa',
'Quem assumiu o poder após o período revolucionário e tornou-se imperador da França?',
'Robespierre',
'Luís XVI',
'Napoleão Bonaparte',
'Carlos Magno',
'C'),

('História','Ensino Médio','Revolução Francesa',
'Qual era o principal objetivo da Revolução Francesa?',
'Expandir o território francês',
'Acabar com os privilégios do Antigo Regime',
'Conquistar a Inglaterra',
'Criar uma monarquia absoluta',
'B'),

('História','Ensino Médio','Revolução Francesa',
'Durante qual fase da Revolução ocorreu o chamado Período do Terror?',
'Diretório',
'Consulado',
'Convenção Nacional',
'Monarquia Constitucional',
'C'),

('História','Ensino Médio','Revolução Francesa',
'Qual acontecimento marcou simbolicamente o início da Revolução Francesa?',
'A coroação de Napoleão',
'A queda da Bastilha',
'A assinatura do Tratado de Paris',
'A Revolução Industrial',
'B');